SHOW TABLES;
SELECT * FROM patient;

SELECT 
s.First_Name,
s.Last_Name,
SUM(b.Net_Amount) AS Total_Revenue
FROM bill b
JOIN treatment_plan tp ON b.Plan_ID = tp.Plan_ID
JOIN staff s ON tp.Doctor_ID = s.Staff_ID
GROUP BY s.Staff_ID;



-- Total Revenue Generated
SELECT SUM(Net_Amount) AS Total_Revenue
FROM bill;


-- 2 Revenue Generated by Each Doctor
SELECT 
s.First_Name,
s.Last_Name,
SUM(b.Net_Amount) AS Total_Revenue
FROM bill b
JOIN treatment_plan tp ON b.Plan_ID = tp.Plan_ID
JOIN staff s ON tp.Doctor_ID = s.Staff_ID
GROUP BY s.Staff_ID;


-- 3 Most Frequently Used Therapy
SELECT 
t.Therapy_Name,
COUNT(ts.Session_ID) AS Usage_Count
FROM therapy_session ts
JOIN therapy t ON ts.Therapy_ID = t.Therapy_ID
GROUP BY t.Therapy_Name
ORDER BY Usage_Count DESC
LIMIT 1;


-- 4 Patient with Highest Bill
SELECT 
p.First_Name,
p.Last_Name,
b.Net_Amount
FROM bill b
JOIN treatment_plan tp ON b.Plan_ID = tp.Plan_ID
JOIN patient p ON tp.Patient_ID = p.Patient_ID
ORDER BY b.Net_Amount DESC
LIMIT 1;


-- 5 Average Cost of Therapies

SELECT AVG(Cost) AS Average_Therapy_Cost
FROM therapy;


-- 6 All Scheduled Appointments
SELECT *
FROM appointment
WHERE Status = 'Scheduled';


-- 7 Active Treatment Plans
SELECT *
FROM treatment_plan
WHERE Plan_Status = 'Active';


-- 8 Doctor with Maximum Treatment Plans
SELECT 
s.First_Name,
s.Last_Name,
COUNT(tp.Plan_ID) AS Total_Plans
FROM treatment_plan tp
JOIN staff s ON tp.Doctor_ID = s.Staff_ID
GROUP BY s.Staff_ID
ORDER BY Total_Plans DESC
LIMIT 1;

-- 9 Total Sessions Conducted by Each Therapist
SELECT 
s.First_Name,
s.Last_Name,
COUNT(ts.Session_ID) AS Total_Sessions
FROM therapy_session ts
JOIN staff s ON ts.Therapist_ID = s.Staff_ID
GROUP BY s.Staff_ID;


-- 10 Inventory Items with Low Stock (<10)
SELECT 
Item_Name,
Quantity_In_Stock
FROM inventory_item
WHERE Quantity_In_Stock < 10;


-- 11 Total Amount Paid for Each Bill


SELECT 
b.Bill_ID,
SUM(p.Amount) AS Total_Paid
FROM bill b
JOIN payment p ON b.Bill_ID = p.Bill_ID
GROUP BY b.Bill_ID;


-- 12 Patients and Their Treatment Packages
SELECT 
p.First_Name,
p.Last_Name,
pk.Package_Name
FROM treatment_plan tp
JOIN patient p ON tp.Patient_ID = p.Patient_ID
JOIN package pk ON tp.Package_ID = pk.Package_ID;


-- 13 Therapies Included in Each Package
SELECT 
pk.Package_Name,
t.Therapy_Name
FROM package_therapy pt
JOIN package pk ON pt.Package_ID = pk.Package_ID
JOIN therapy t ON pt.Therapy_ID = t.Therapy_ID;


-- 14 Total Inventory Usage per Session
SELECT 
Session_ID,
SUM(Quantity_Used) AS Total_Usage
FROM session_inventory_usage
GROUP BY Session_ID;


-- 15 Patients Who Have Completed Sessions
SELECT DISTINCT
p.First_Name,
p.Last_Name
FROM therapy_session ts
JOIN treatment_plan tp ON ts.Plan_ID = tp.Plan_ID
JOIN patient p ON tp.Patient_ID = p.Patient_ID
WHERE ts.Session_Status = 'Completed';




